server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhangbaohpu/basespringcloud.git
          search-paths: config
          username: 18300602603
          password: 153514zb
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
